### ISSUE TITLE
Can't access proxy2.test

### ISSUE THREAD

**Issue by Attect** [inaz2/proxy2#3]
Can't get the CA certificate

**Comment by inaz2** [comment]
Did you execute `setup_https_intercept.sh` first?
Please show me the traceback of proxy2.py at that time :confused:

**Comment by inaz2** [comment]
Close because of no reply.

**Comment by inaz2** [comment]
#16

**Comment by simkoc** [comment]
I had a similar problem. The certificates where not found/loaded. However the fix was trivial. 

I started the proxy from a different folder via a bash script and thus the working directory was the one of the bash script whereas the certificates where stored in the proxy folder. Consequently they were not found. The solution was to pushd/popd the correct proxy directory before starting the proxy. The documentation for the https intercept does not explain that this could become an issue and it might be a valuable note for future users. In retrospective it is a quite obvious, though.

**Comment by inaz2** [comment]
@simkoc Thank you for your report. I changed to set absolute path of them at run-time.
